services:
  - type: web
    name: discord-bot
    env: node
    plan: free
    buildCommand: "npm ci"
    startCommand: "node bot.js"
    healthCheckPath: "/health"
    autoDeploy: true
    envVars:
      - key: TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: GUILD_ID
        sync: false
      - key: SELF_PING_URL
        value: "https://<your-service>.onrender.com/health"
